import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    colors: {
      background: '#fcf8ff',
      'on-background': '#181445',
      'on-surface': '#181445',
      'on-surface-variant': '#434655',
      surface: '#fcf8ff',
      'surface-container': '#efebff',
      'surface-container-low': '#f6f2ff',
      'surface-container-lowest': '#ffffff',
      'surface-container-high': '#e9e5ff',
      'surface-container-highest': '#e3dfff',
      'surface-variant': '#e3dfff',
      'surface-dim': '#dad6ff',
      'surface-bright': '#fcf8ff',
      'surface-tint': '#0053db',
      primary: '#004ac6',
      'primary-container': '#2563eb',
      'primary-fixed': '#dbe1ff',
      'primary-fixed-dim': '#b4c5ff',
      'on-primary': '#ffffff',
      'on-primary-container': '#eeefff',
      'on-primary-fixed': '#00174b',
      'on-primary-fixed-variant': '#003ea8',
      secondary: '#4b41e1',
      'secondary-container': '#645efb',
      'secondary-fixed': '#e2dfff',
      'secondary-fixed-dim': '#c3c0ff',
      'on-secondary': '#ffffff',
      'on-secondary-container': '#fffbff',
      'on-secondary-fixed': '#0f0069',
      'on-secondary-fixed-variant': '#3323cc',
      tertiary: '#3e3fcc',
      'tertiary-container': '#585be6',
      'tertiary-fixed': '#e1e0ff',
      'tertiary-fixed-dim': '#c0c1ff',
      'on-tertiary': '#ffffff',
      'on-tertiary-container': '#f1eeff',
      'on-tertiary-fixed': '#07006c',
      'on-tertiary-fixed-variant': '#2f2ebe',
      error: '#ba1a1a',
      'error-container': '#ffdad6',
      'on-error': '#ffffff',
      'on-error-container': '#93000a',
      outline: '#737686',
      'outline-variant': '#c3c6d7',
      'inverse-surface': '#2d2a5b',
      'inverse-on-surface': '#f3eeff',
      'inverse-primary': '#b4c5ff',
      white: '#ffffff',
      black: '#000000',
    },
    spacing: {
      xs: '4px',
      sm: '8px',
      md: '16px',
      lg: '24px',
      xl: '48px',
      unit: '4px',
      gutter: '24px',
      'margin-mobile': '16px',
      'container-max': '1280px',
    },
    fontFamily: {
      sans: ["'Assistant', 'system-ui', 'sans-serif'"],
      'body-md': ["'Assistant'"],
      'body-lg': ["'Assistant'"],
      'headline-lg': ["'Assistant'"],
      'headline-xl': ["'Assistant'"],
      'label-md': ["'Assistant'"],
      caption: ["'Assistant'"],
      'display-lg': ["'Assistant'"],
      'display-lg-mobile': ["'Assistant'"],
    },
    fontSize: {
      caption: ['12px', { lineHeight: '1.4', fontWeight: '400' }],
      'label-md': ['14px', { lineHeight: '1.4', fontWeight: '600' }],
      'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
      'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
      'headline-lg': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
      'headline-xl': ['32px', { lineHeight: '1.3', fontWeight: '700' }],
      'display-lg-mobile': ['36px', { lineHeight: '1.2', fontWeight: '700' }],
      'display-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
    },
    borderRadius: {
      DEFAULT: '0.25rem',
      lg: '0.5rem',
      xl: '0.75rem',
      full: '9999px',
    },
    extend: {
      animation: {
        ping: 'ping 2s cubic-bezier(0, 0, 0.2, 1) infinite',
      },
    },
  },
  plugins: [],
};

export default config;
